#
#this is our first deployment manifest file

kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deploy
  namespace: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: nginx-dep-template
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 110Mi
            limits:
              cpu: 150m
              memory: 200Mi

          volumeMounts:
            - mountPath: /var/www/html
              name: nginx-volume
          
      volumes:
        - name: nginx-volume
          persistentVolumeClaim:
            claimName: local-pvc

