kind: Pod
apiVersion: v1
metadata:
  name: busybox
  labels: 
    app: busybox
    environment: dev

spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ["sh", "-c", "echo Hello From Busybox && sleep 360"]
